### PR TITLE
protobuf-lite: Update namespace

### PR DESCRIPTION
**Pull request by rudraps0x63**
Change namespace so as not to interfere with other libraries using the same library.

### CODE REVIEW

**Review by olyasir — APPROVED** [review]
looks good

**Review by olyasir — APPROVED** [review]
looks good

**Review by olyasir — APPROVED** [review]

**Review by olyasir — APPROVED** [review]
k

**Review by olyasir — APPROVED** [review]
k

**Review by olyasir — APPROVED** [review]

**Review by olyasir — APPROVED** [review]

**Review by chetasr — APPROVED** [review]

**Review by subashsn — APPROVED** [review]

**Pull request merged**
